export const init1 = [
    'Booting...',
    'Looking for updates...',
    'Downloading updates...',
    'Almost done...',
];

export const init2 = [
    'Gathering info...',
    'Looking for modules...',
    'Modules found!',
    'Loading modules...',
    'Modules loaded!',
    'Screen detected!',
    'Audio device detected!',
    'Geolocation recorded!',
    'Loading episode...',
    'Episode loaded!',
    'Loading colors...',
    'Colors loaded!',
    'Loading text...',
    'Text loaded!',
    'Loading audio...',
    'Audio loaded!',
    'Loading intro animation...',
    'Intro animation loaded!',
    'Loading terminal theme...',
    'Terminal theme applied!',
    'Finishing up a few final things...',
    'Almost there...',
    'Starting terminal!',
];

export const mateInstall = [
    'me@myTerminal> sudo pacman -S mate mate-extra --noconfirm',
    ':: There are 14 members in group mate:',
    ':: Repository community',
    '   1) caja  2) marco  3) mate-backgrounds  4) mate-control-center  5) mate-desktop  6) mate-icon-theme  7) mate-menus  8) mate-notification-daemon  9) mate-panel  10) mate-polkit  11) mate-session-manager  12) mate-settings-daemon  13) mate-themes  14) mate-user-guide',
    '',
    'Enter a selection (default=all): ',
    ':: There are 23 members in group mate-extra:',
    ':: Repository community',
    '   1) atril  2) caja-image-converter  3) caja-open-terminal  4) caja-sendto  5) caja-share  6) caja-wallpaper  7) caja-xattr-tags  8) engrampa  9) eom  10) mate-applets  11) mate-calc  12) mate-icon-theme-faenza  13) mate-media  14) mate-netbook  15) mate-power-manager  16) mate-screensaver  17) mate-sensors-applet  18) mate-system-monitor  19) mate-terminal  20) mate-user-share  21) mate-utils  22) mozo  23) pluma',
    '',
    'Enter a selection (default=all): ',
    'resolving dependencies...',
    'looking for conflicting packages...',
    '',
    'Packages (37) atril-1.24.0-2  caja-1.24.0-1  caja-image-converter-1.24.1-1  caja-open-terminal-1.24.1-1  caja-sendto-1.24.1-1  caja-share-1.24.1-1  caja-wallpaper-1.24.1-1  caja-xattr-tags-1.24.1-1  engrampa-1.24.1-1  eom-1.24.1-1  marco-1.24.1-1  mate-applets-1.24.1-1  mate-backgrounds-1.24.1-1  mate-calc-1.24.1-1  mate-control-center-1.24.1-1  mate-desktop-1.24.1-1  mate-icon-theme-1.24.0-1  mate-icon-theme-faenza-1.20.0-2  mate-media-1.24.1-1  mate-menus-1.24.1-1  mate-netbook-1.24.0-1  mate-notification-daemon-1.24.1-1  mate-panel-1.24.1-1  mate-polkit-1.24.0-1  mate-power-manager-1.24.1-1  mate-screensaver-1.24.1-1  mate-sensors-applet-1.24.1-1  mate-session-manager-1.24.1-1  mate-settings-daemon-1.24.1-1  mate-system-monitor-1.24.0-1  mate-terminal-1.24.1-1  mate-themes-3.22.21-1  mate-user-guide-1.24.0-1  mate-user-share-1.24.0-1  mate-utils-1.24.0-1  mozo-1.24.0-1  pluma-1.24.1-1',
    '',
    'Total Installed Size:  516.21 MiB',
    '',
    ':: Proceed with installation? [Y/n] ',
    'checking keyring...',
    'checking package integrity...',
    'loading package files...',
    'checking for file conflicts...',
    'checking available disk space...',
    ':: Processing package changes...',
    'installing mate-desktop...',
    'installing caja...',
    'Optional dependencies for caja',
    '    gstreamer: automatic media playback when mouseover [installed]',
    'installing marco...',
    'installing mate-backgrounds...',
    'installing mate-menus...',
    'installing mate-settings-daemon...',
    'Optional dependencies for mate-settings-daemon',
    '    libcanberra-pulse: PulseAudio support [installed]',
    '    pulseaudio-alsa: PulseAudio support [installed]',
    'installing mate-control-center...',
    'installing mate-icon-theme...',
    'installing mate-notification-daemon...',
    'installing mate-panel...',
    'installing mate-polkit...',
    'installing mate-session-manager...',
    'Optional dependencies for mate-session-manager',
    '    gnome-keyring: keyring support [installed]',
    '    xdg-user-dirs-gtk: manage user directories [installed]',
    'installing mate-themes...',
    'Optional dependencies for mate-themes',
    '    gtk-engines: for gtk2 themes',
    '    gtk-engine-murrine: for gtk2 themes',
    '    mate-icon-theme: default icon theme [installed]',
    'installing mate-user-guide...',
    'installing atril...',
    'Optional dependencies for atril',
    '    caja: Document Properties extension [installed]',
    '    texlive-bin: DVI support',
    'installing caja-image-converter...',
    'installing caja-open-terminal...',
    'installing caja-sendto...',
    'Optional dependencies for caja-sendto',
    '    pidgin: Support for sending to instant messaging networks.',
    '    gajim: Support for sending to XMPP.',
    'installing caja-share...',
    'installing caja-wallpaper...',
    'installing caja-xattr-tags...',
    'installing engrampa...',
    'Optional dependencies for engrampa',
    '    caja: Caja support [installed]',
    '    p7zip: 7Z and ARJ archive support [installed]',
    '    unace: ACE archive support',
    '    unrar: RAR archive support',
    '    brotli: Brotli compression support [installed]',
    'installing eom...',
    'installing mate-applets...',
    'Optional dependencies for mate-applets',
    '    fortune-mod: for displaying fortune cookies in the Wanda the Fish applet',
    '    gucharmap: character picker applet',
    'installing mate-calc...',
    'installing mate-icon-theme-faenza...',
    'installing mate-media...',
    'installing mate-netbook...',
    'installing mate-power-manager...',
    'Optional dependencies for mate-power-manager',
    '    mate-panel: Set brightness and inhibit power management from the panel [installed]',
    'installing mate-screensaver...',
    'installing mate-sensors-applet...',
    'installing mate-system-monitor...',
    'installing mate-terminal...',
    'installing mate-user-share...',
    'Optional dependencies for mate-user-share',
    '    caja: File sharing extension [installed]',
    'installing mate-utils...',
    'Optional dependencies for mate-utils',
    '    mate-panel: Look up words in dictionaries from the panel [installed]',
    'installing mozo...',
    'installing pluma...',
    'Optional dependencies for pluma',
    '    python-gobject: to use the python plugins [installed]',
    ':: Running post-transaction hooks...',
    '(1/7) Reloading device manager configuration...',
    '(2/7) Arming ConditionNeedsUpdate...',
    '(3/7) Reloading system bus configuration...',
    '(4/7) Compiling GSettings XML schema files...',
    '(5/7) Updating icon theme caches...',
    '(6/7) Updating the desktop file MIME type cache...',
    '(7/7) Updating the MIME type database...',
    'Complete!\n',
    'me@myTerminal>'
];
